# Setup Node
language: node_js
node_js:
  - 11

# Setup Yarn
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true

# Install Dependencies
install: yarn

# Run Test and then run Build
script: yarn test && yarn build
